/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CheckersGame */

#ifndef _Included_CheckersGame
#define _Included_CheckersGame
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CheckersGame
 * Method:    initGame
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_CheckersGame_initGame
  (JNIEnv *, jobject);

/*
 * Class:     CheckersGame
 * Method:    getBoardState
 * Signature: (J)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_CheckersGame_getBoardState
  (JNIEnv *, jobject, jlong);

/*
 * Class:     CheckersGame
 * Method:    validateMove
 * Signature: (JIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_CheckersGame_validateMove
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint);

/*
 * Class:     CheckersGame
 * Method:    executeMove
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_CheckersGame_executeMove
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint);

/*
 * Class:     CheckersGame
 * Method:    getPlayerOneCaptured
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_CheckersGame_getPlayerOneCaptured
  (JNIEnv *, jobject, jlong);

/*
 * Class:     CheckersGame
 * Method:    getPlayerTwoCaptured
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_CheckersGame_getPlayerTwoCaptured
  (JNIEnv *, jobject, jlong);

/*
 * Class:     CheckersGame
 * Method:    isGameOver
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_CheckersGame_isGameOver
  (JNIEnv *, jobject, jlong);

/*
 * Class:     CheckersGame
 * Method:    getWinner
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_CheckersGame_getWinner
  (JNIEnv *, jobject, jlong);

/*
 * Class:     CheckersGame
 * Method:    getCurrentPlayer
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_CheckersGame_getCurrentPlayer
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
